import type { Metadata } from 'next';
import './globals.css';
import Background from '@/components/primitives/Background';

export const metadata: Metadata = {
  title: '세라복.모에 커모지 신청 페이지',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="font-sans">
        {children}
        <Background />
      </body>
    </html>
  );
}
